name: Reusable Build and Deploy

on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: latest
    secrets:
      REGISTRY_TOKEN:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image name (lowercase)
        run: |
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}/${{ inputs.app }}:${{ inputs.tag }}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}

      - name: Deploy placeholder
        run: echo "🚀 Desplegando ${{ env.IMAGE_NAME }}"
